<?php return array(
    'root' => array(
        'name' => 'jsongerber/wp-sync-db',
        'pretty_version' => 'dev-master',
        'version' => 'dev-master',
        'reference' => '807f95e22998919856728294cf4e245bdc7995d6',
        'type' => 'wordpress-plugin',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        'dealerdirect/phpcodesniffer-composer-installer' => array(
            'pretty_version' => 'v1.2.0',
            'version' => '1.2.0.0',
            'reference' => '845eb62303d2ca9b289ef216356568ccc075ffd1',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../dealerdirect/phpcodesniffer-composer-installer',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'jsongerber/wp-sync-db' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '807f95e22998919856728294cf4e245bdc7995d6',
            'type' => 'wordpress-plugin',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'php-stubs/wordpress-globals' => array(
            'pretty_version' => 'v0.2.0',
            'version' => '0.2.0.0',
            'reference' => '748a1fb2ae8fda94844bd0545935095dbf404b32',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-stubs/wordpress-globals',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'php-stubs/wordpress-stubs' => array(
            'pretty_version' => 'v6.9.1',
            'version' => '6.9.1.0',
            'reference' => 'f12220f303e0d7c0844c0e5e957b0c3cee48d2f7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-stubs/wordpress-stubs',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'php-stubs/wp-cli-stubs' => array(
            'pretty_version' => 'v2.12.0',
            'version' => '2.12.0.0',
            'reference' => 'af16401e299a3fd2229bd0fa9a037638a4174a9d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-stubs/wp-cli-stubs',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpcsstandards/phpcsextra' => array(
            'pretty_version' => '1.5.0',
            'version' => '1.5.0.0',
            'reference' => 'b598aa890815b8df16363271b659d73280129101',
            'type' => 'phpcodesniffer-standard',
            'install_path' => __DIR__ . '/../phpcsstandards/phpcsextra',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpcsstandards/phpcsutils' => array(
            'pretty_version' => '1.2.2',
            'version' => '1.2.2.0',
            'reference' => 'c216317e96c8b3f5932808f9b0f1f7a14e3bbf55',
            'type' => 'phpcodesniffer-standard',
            'install_path' => __DIR__ . '/../phpcsstandards/phpcsutils',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpstan/phpstan' => array(
            'pretty_version' => '2.1.46',
            'version' => '2.1.46.0',
            'reference' => 'a193923fc2d6325ef4e741cf3af8c3e8f54dbf25',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpstan/phpstan',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'rector/rector' => array(
            'pretty_version' => '2.4.1',
            'version' => '2.4.1.0',
            'reference' => '000b7050b9e4fe98db2192971e56eb0b302b3feb',
            'type' => 'library',
            'install_path' => __DIR__ . '/../rector/rector',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'squizlabs/php_codesniffer' => array(
            'pretty_version' => '3.13.5',
            'version' => '3.13.5.0',
            'reference' => '0ca86845ce43291e8f5692c7356fccf3bcf02bf4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../squizlabs/php_codesniffer',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'wp-coding-standards/wpcs' => array(
            'pretty_version' => '3.3.0',
            'version' => '3.3.0.0',
            'reference' => '7795ec6fa05663d716a549d0b44e47ffc8b0d4a6',
            'type' => 'phpcodesniffer-standard',
            'install_path' => __DIR__ . '/../wp-coding-standards/wpcs',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
    ),
);
