<?php return array(
    'root' => array(
        'name' => 'jsongerber/wp-sync-db',
        'pretty_version' => 'dev-master',
        'version' => 'dev-master',
        'reference' => '26d53defffb03ddb98cb4d95c033c5bd0f5b23bb',
        'type' => 'wordpress-plugin',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        'jsongerber/wp-sync-db' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '26d53defffb03ddb98cb4d95c033c5bd0f5b23bb',
            'type' => 'wordpress-plugin',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'php-stubs/wordpress-globals' => array(
            'pretty_version' => 'v0.2.0',
            'version' => '0.2.0.0',
            'reference' => '748a1fb2ae8fda94844bd0545935095dbf404b32',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-stubs/wordpress-globals',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'php-stubs/wordpress-stubs' => array(
            'pretty_version' => 'v6.9.1',
            'version' => '6.9.1.0',
            'reference' => 'f12220f303e0d7c0844c0e5e957b0c3cee48d2f7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-stubs/wordpress-stubs',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'php-stubs/wp-cli-stubs' => array(
            'pretty_version' => 'v2.12.0',
            'version' => '2.12.0.0',
            'reference' => 'af16401e299a3fd2229bd0fa9a037638a4174a9d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-stubs/wp-cli-stubs',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpstan/phpstan' => array(
            'pretty_version' => '2.1.46',
            'version' => '2.1.46.0',
            'reference' => 'a193923fc2d6325ef4e741cf3af8c3e8f54dbf25',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpstan/phpstan',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'rector/rector' => array(
            'pretty_version' => '2.4.1',
            'version' => '2.4.1.0',
            'reference' => '000b7050b9e4fe98db2192971e56eb0b302b3feb',
            'type' => 'library',
            'install_path' => __DIR__ . '/../rector/rector',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
    ),
);
